// Code generated by goyacc - DO NOT EDIT.

package main

import __yyfmt__ "fmt"

import (
	"fmt"
)

type yySymType struct {
	yys int
	Int int
	Str string
}

type yyXError struct {
	state, xsym int
}

const (
	yyDefault = 57348
	yyEofCode = 57344
	INTEGER   = 57346
	VARIABLE  = 57347
	yyErrCode = 57345

	yyMaxDepth = 200
	yyTabOfs   = -12
)

var (
	yyPrec = map[int]int{
		'+': 0,
		'-': 0,
		'*': 1,
		'/': 1,
	}

	yyXLAT = map[int]int{
		42:    0,  // '*' (11x)
		43:    1,  // '+' (11x)
		45:    2,  // '-' (11x)
		47:    3,  // '/' (11x)
		10:    4,  // '\n' (11x)
		40:    5,  // '(' (9x)
		57346: 6,  // INTEGER (9x)
		57347: 7,  // VARIABLE (9x)
		41:    8,  // ')' (8x)
		57349: 9,  // expr (7x)
		57344: 10, // $end (3x)
		61:    11, // '=' (1x)
		57350: 12, // program (1x)
		57351: 13, // statement (1x)
		57348: 14, // $default (0x)
		57345: 15, // error (0x)
	}

	yySymNames = []string{
		"'*'",
		"'+'",
		"'-'",
		"'/'",
		"'\\n'",
		"'('",
		"INTEGER",
		"VARIABLE",
		"')'",
		"expr",
		"$end",
		"'='",
		"program",
		"statement",
		"$default",
		"error",
	}

	yyTokenLiteralStrings = map[int]string{}

	yyReductions = map[int]struct{ xsym, components int }{
		0:  {0, 1},
		1:  {12, 3},
		2:  {12, 0},
		3:  {13, 1},
		4:  {13, 3},
		5:  {9, 1},
		6:  {9, 1},
		7:  {9, 3},
		8:  {9, 3},
		9:  {9, 3},
		10: {9, 3},
		11: {9, 3},
	}

	yyXErrors = map[yyXError]string{}

	yyParseTab = [21][]uint8{
		// 0
		{5: 10, 10, 10, 10: 10, 12: 13},
		{5: 18, 17, 16, 9: 15, 12, 13: 14},
		{4: 32},
		{23, 21, 22, 24, 9},
		{6, 6, 6, 6, 6, 11: 30},
		// 5
		{7, 7, 7, 7, 7, 8: 7},
		{5: 18, 17, 19, 9: 20},
		{6, 6, 6, 6, 6, 8: 6},
		{23, 21, 22, 24, 8: 25},
		{5: 18, 17, 19, 9: 29},
		// 10
		{5: 18, 17, 19, 9: 28},
		{5: 18, 17, 19, 9: 27},
		{5: 18, 17, 19, 9: 26},
		{1, 1, 1, 1, 1, 8: 1},
		{2, 2, 2, 2, 2, 8: 2},
		// 15
		{3, 3, 3, 3, 3, 8: 3},
		{23, 4, 4, 24, 4, 8: 4},
		{23, 5, 5, 24, 5, 8: 5},
		{5: 18, 17, 19, 9: 31},
		{23, 21, 22, 24, 8},
		// 20
		{5: 11, 11, 11, 10: 11},
	}
)

var yyDebug = 0

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyLexerEx interface {
	yyLexer
	Reduced(rule, state int, lval *yySymType) bool
}

func yySymName(c int) (s string) {
	x, ok := yyXLAT[c]
	if ok {
		return yySymNames[x]
	}

	if c < 0x7f {
		return __yyfmt__.Sprintf("%q", c)
	}

	return __yyfmt__.Sprintf("%d", c)
}

func yylex1(yylex yyLexer, lval *yySymType) (n int) {
	n = yylex.Lex(lval)
	if n <= 0 {
		n = yyEofCode
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("\nlex %s(%#x %d), lval: %+v\n", yySymName(n), n, n, lval)
	}
	return n
}

func yyParse(yylex yyLexer) int {
	const yyError = 15

	yyEx, _ := yylex.(yyLexerEx)
	var yyn int
	var yylval yySymType
	var yyVAL yySymType
	yyS := make([]yySymType, 200)

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yyerrok := func() {
		if yyDebug >= 2 {
			__yyfmt__.Printf("yyerrok()\n")
		}
		Errflag = 0
	}
	_ = yyerrok
	yystate := 0
	yychar := -1
	var yyxchar int
	var yyshift int
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	if yychar < 0 {
		yylval.yys = yystate
		yychar = yylex1(yylex, &yylval)
		var ok bool
		if yyxchar, ok = yyXLAT[yychar]; !ok {
			yyxchar = len(yySymNames) // > tab width
		}
	}
	if yyDebug >= 4 {
		var a []int
		for _, v := range yyS[:yyp+1] {
			a = append(a, v.yys)
		}
		__yyfmt__.Printf("state stack %v\n", a)
	}
	row := yyParseTab[yystate]
	yyn = 0
	if yyxchar < len(row) {
		if yyn = int(row[yyxchar]); yyn != 0 {
			yyn += yyTabOfs
		}
	}
	switch {
	case yyn > 0: // shift
		yychar = -1
		yyVAL = yylval
		yystate = yyn
		yyshift = yyn
		if yyDebug >= 2 {
			__yyfmt__.Printf("shift, and goto state %d\n", yystate)
		}
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	case yyn < 0: // reduce
	case yystate == 1: // accept
		if yyDebug >= 2 {
			__yyfmt__.Println("accept")
		}
		goto ret0
	}

	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			if yyDebug >= 1 {
				__yyfmt__.Printf("no action for %s in state %d\n", yySymName(yychar), yystate)
			}
			msg, ok := yyXErrors[yyXError{yystate, yyxchar}]
			if !ok {
				msg, ok = yyXErrors[yyXError{yystate, -1}]
			}
			if !ok && yyshift != 0 {
				msg, ok = yyXErrors[yyXError{yyshift, yyxchar}]
			}
			if !ok {
				msg, ok = yyXErrors[yyXError{yyshift, -1}]
			}
			if yychar > 0 {
				ls := yyTokenLiteralStrings[yychar]
				if ls == "" {
					ls = yySymName(yychar)
				}
				if ls != "" {
					switch {
					case msg == "":
						msg = __yyfmt__.Sprintf("unexpected %s", ls)
					default:
						msg = __yyfmt__.Sprintf("unexpected %s, %s", ls, msg)
					}
				}
			}
			if msg == "" {
				msg = "syntax error"
			}
			yylex.Error(msg)
			Nerrs++
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				row := yyParseTab[yyS[yyp].yys]
				if yyError < len(row) {
					yyn = int(row[yyError]) + yyTabOfs
					if yyn > 0 { // hit
						if yyDebug >= 2 {
							__yyfmt__.Printf("error recovery found error shift in state %d\n", yyS[yyp].yys)
						}
						yystate = yyn /* simulate a shift of "error" */
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery failed\n")
			}
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yySymName(yychar))
			}
			if yychar == yyEofCode {
				goto ret1
			}

			yychar = -1
			goto yynewstate /* try again in the same state */
		}
	}

	r := -yyn
	x0 := yyReductions[r]
	x, n := x0.xsym, x0.components
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= n
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	exState := yystate
	yystate = int(yyParseTab[yyS[yyp].yys][x]) + yyTabOfs
	/* reduction by production r */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce using rule %v (%s), and goto state %d\n", r, yySymNames[x], yystate)
	}

	switch r {
	case 3:
		{
			fmt.Println(yyS[yypt-0].Int)
		}
	case 4:
		{
			yylex.(*Lexer).Sym[yyS[yypt-2].Str] = yyS[yypt-0].Int
		}
	case 6:
		{
			yyVAL.Int = yylex.(*Lexer).Sym[yyS[yypt-0].Str]
		}
	case 7:
		{
			yyVAL.Int = yyS[yypt-2].Int + yyS[yypt-0].Int
		}
	case 8:
		{
			yyVAL.Int = yyS[yypt-2].Int - yyS[yypt-0].Int
		}
	case 9:
		{
			yyVAL.Int = yyS[yypt-2].Int * yyS[yypt-0].Int
		}
	case 10:
		{
			yyVAL.Int = yyS[yypt-2].Int / yyS[yypt-0].Int
		}
	case 11:
		{
			yyVAL.Int = yyS[yypt-1].Int
		}

	}

	if yyEx != nil && yyEx.Reduced(r, exState, &yyVAL) {
		return -1
	}
	goto yystack /* stack new state and value */
}
